package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, May 18, 2026 7:27:06 PM NPT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
